### ISSUE TITLE
Pi Hole 5 ?

### ISSUE THREAD

**Issue by Rar9** [ndfred/unifi-pi-hole#15]
Hi, 
If I understand this right there is no Extra Hardware required as Pi-Hole is installed on the USG.

Will this script install the new Pi Hole 5 version on a USG Pro?
How is the Pi Hole Gui reachable for setup?

**Comment by ndfred** [comment]
The idea here is to re-create the Pi-Hole blocking list functionality within the USG, not port the full PiHole setup over which would be a much more invasive operation. If you need full PiHole functionality, I would suggest getting a separate Pi to host it.
